const std = @import("std");

pub const header = @import("header.zig");
pub const pointer = @import("pointer.zig");
pub const pheap = @import("pheap.zig");
pub const allocator = @import("allocator.zig");
pub const wal = @import("wal.zig");
pub const transaction = @import("transaction.zig");
pub const recovery = @import("recovery.zig");
pub const concurrency = @import("concurrency.zig");
pub const gc = @import("gc.zig");
pub const snapshot = @import("snapshot.zig");
pub const security = @import("security.zig");
pub const schema = @import("schema.zig");
pub const api = @import("api.zig");
pub const mem_utils = @import("mem_utils.zig");
pub const topology = @import("topology.zig");
pub const numa = @import("numa.zig");
pub const simd = @import("simd.zig");
pub const seqlock = @import("seqlock.zig");
pub const tsc = @import("tsc.zig");
pub const htm = @import("htm.zig");
pub const ans = @import("ans.zig");
pub const replay = @import("replay.zig");
pub const iouring = @import("iouring.zig");
pub const jit_alloc = @import("jit_alloc.zig");
pub const gpu = @import("gpu.zig");
pub const repair = @import("repair.zig");
pub const benchmark = @import("benchmark.zig");
pub const inspect = @import("inspect.zig");
pub const rdma = @import("rdma.zig");
pub const rdma_channel = @import("rdma_channel.zig");
pub const dhtm = @import("dhtm.zig");

pub const runtime = @import("runtime.zig");
pub const tokenizer = @import("tokenizer.zig");
pub const json = @import("json.zig");
pub const kv = @import("kv.zig");
pub const bm25 = @import("bm25.zig");
pub const vector = @import("vector.zig");
pub const record = @import("record.zig");
pub const server = @import("server.zig");
pub const cli = @import("cli.zig");
pub const database = @import("database.zig");
pub const types = @import("types.zig");
pub const io = @import("io.zig");
pub const memory = @import("memory.zig");
pub const tensor = @import("tensor.zig");
pub const ssi = @import("ssi.zig");
pub const ranker = @import("ranker.zig");
pub const rank_index = @import("rank_index.zig");

pub const cloud = struct {
    pub const apikey = @import("cloud/apikey.zig");
    pub const tenant = @import("cloud/tenant.zig");
    pub const registry = @import("cloud/registry.zig");
    pub const sandbox = @import("cloud/sandbox.zig");
    pub const ipc = @import("cloud/ipc.zig");
    pub const process_table = @import("cloud/process_table.zig");
    pub const router = @import("cloud/router.zig");
    pub const registration = @import("cloud/registration.zig");
    pub const wal_transport = @import("cloud/wal_transport.zig");
};

pub const Runtime = runtime.Runtime;
pub const RuntimeConfig = runtime.RuntimeConfig;
pub const RuntimeStats = runtime.RuntimeStats;

pub const Database = database.Database;
pub const DatabaseConfig = database.DatabaseConfig;

pub const PersistentStore = api.PersistentStore;
pub const PersistentHeap = pheap.PersistentHeap;
pub const PersistentAllocator = allocator.PersistentAllocator;
pub const WAL = wal.WAL;
pub const TransactionManager = transaction.TransactionManager;
pub const Transaction = transaction.Transaction;
pub const RecoveryEngine = recovery.RecoveryEngine;
pub const SnapshotManager = snapshot.SnapshotManager;
pub const SecurityManager = security.SecurityManager;
pub const SchemaRegistry = schema.SchemaRegistry;
pub const RefCountGC = gc.RefCountGC;

pub const RelativePtr = pointer.RelativePtr;
pub const PersistentPtr = pointer.PersistentPtr;

pub const KvStore = kv.KvStore;
pub const Bm25Index = bm25.Bm25Index;
pub const VectorIndex = vector.VectorIndex;
pub const Record = record.Record;
pub const RecordWriter = record.RecordWriter;
pub const RecordReader = record.RecordReader;
pub const Server = server.Server;
pub const ServerConfig = server.ServerConfig;
pub const Tensor = tensor.Tensor;
pub const SSI = ssi.SSI;
pub const Ranker = ranker.Ranker;
pub const RankerConfig = ranker.RankerConfig;
pub const RankedSegment = types.RankedSegment;
pub const BitSet = types.BitSet;
pub const PRNG = types.PRNG;
pub const Fixed32_32 = types.Fixed32_32;
pub const stableHash = io.stableHash;
pub const RankIndex = rank_index.RankIndex;
pub const RankIndexConfig = rank_index.RankIndexConfig;

test {
    std.testing.refAllDecls(@This());
    std.testing.refAllDecls(header);
    std.testing.refAllDecls(pointer);
    std.testing.refAllDecls(pheap);
    std.testing.refAllDecls(allocator);
    std.testing.refAllDecls(wal);
    std.testing.refAllDecls(transaction);
    std.testing.refAllDecls(recovery);
    std.testing.refAllDecls(concurrency);
    std.testing.refAllDecls(gc);
    std.testing.refAllDecls(snapshot);
    std.testing.refAllDecls(security);
    std.testing.refAllDecls(schema);
    std.testing.refAllDecls(api);
    std.testing.refAllDecls(mem_utils);
    std.testing.refAllDecls(topology);
    std.testing.refAllDecls(numa);
    std.testing.refAllDecls(simd);
    std.testing.refAllDecls(seqlock);
    std.testing.refAllDecls(tsc);
    std.testing.refAllDecls(htm);
    std.testing.refAllDecls(ans);
    std.testing.refAllDecls(replay);
    std.testing.refAllDecls(iouring);
    std.testing.refAllDecls(jit_alloc);
    std.testing.refAllDecls(gpu);
    std.testing.refAllDecls(repair);
    std.testing.refAllDecls(benchmark);
    std.testing.refAllDecls(inspect);
    std.testing.refAllDecls(rdma);
    std.testing.refAllDecls(rdma_channel);
    std.testing.refAllDecls(dhtm);
    std.testing.refAllDecls(runtime);
    std.testing.refAllDecls(tokenizer);
    std.testing.refAllDecls(json);
    std.testing.refAllDecls(kv);
    std.testing.refAllDecls(bm25);
    std.testing.refAllDecls(vector);
    std.testing.refAllDecls(record);
    std.testing.refAllDecls(server);
    std.testing.refAllDecls(cli);
    std.testing.refAllDecls(database);
    std.testing.refAllDecls(types);
    std.testing.refAllDecls(io);
    std.testing.refAllDecls(memory);
    std.testing.refAllDecls(tensor);
    std.testing.refAllDecls(ssi);
    std.testing.refAllDecls(ranker);
    std.testing.refAllDecls(rank_index);
}
